name: flutter_app
description: new flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0+150

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:

  dartz: ^0.9.2
  #使用SVG图片
  flutter_svg: ^0.19.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^0.1.3
  #object serializable
  # json_serializable: ^3.2.5
  #闲鱼-应用框架
  fish_redux: ^0.3.3

  # mime: ^0.9.6+3
  mime_type: ^0.3.2
  # google_fonts: ^1.1.0
  #常亮
  wakelock: ^0.1.4+1

  draggable_scrollbar: ^0.0.4

  # # network framework
  # dio: ^3.0.8

  #文件地址配置
  path_provider: ^1.6.1
  #事件发送器

  event_bus: ^1.1.1

  #获取设备Id
  device_info: ^0.4.2+10
  #对话框
  progress_dialog: ^1.2.2

  #网络连接状态
  connectivity: ^1.0.0

  #下拉刷新以及上拉加载
  flutter_easyrefresh: 2.1.6
  permission_handler: ^5.0.1+1

  #格式化
  sprintf: ^4.0.2
  #弹窗
  flutter_custom_dialog: ^1.0.16
  #分页
  flutter_swiper: ^1.1.6
  #动画
  flutter_animation_set: ^0.0.4
  #时间操作
  common_utils: ^1.2.1
  
  #uuid生成器
  uuid: ^2.0.4

  #http网络库
  http: ^0.12.0+4
  # flutter_sequence_animation: ^3.0.1

  #sqlite数据库
  sqflite: ^1.2.1

  video_player: ^1.0.1
  #录制视频
  camera: ^0.5.7+4

  # # 缓存
  # flutter_cache_manager:
  #   path: ./flutter_cache_manager
  #安装apk
  install_plugin: ^2.0.1
  # # 图片框架
  # cached_network_image:
  #   path: ./cached_network_image

  #城市列表
  azlistview: 1.0.1 #latest version

  lpinyin: ^1.0.9

  #瀑布流
  flutter_staggered_grid_view: "^0.3.4"

  #日期选择控件
  flutter_datetime_picker: ^1.3.8
  #弹出提示
  fluttertoast: ^3.1.3

  #二维码
  qr_flutter: ^3.2.0

  image_gallery_saver: ^1.6.7 #保存图片到相册

  #图片压缩
  # flutter_image_compress: ^0.6.5+1
  flutter_native_image: ^0.0.5

  extended_nested_scroll_view: ^0.4.0

  #加密
  encrypt: ^4.0.0

  #视频编码
  # flutter_ffmpeg: ^0.2.10

  #包信息
  package_info: 0.4.0+14

  #存储加密
  flutter_secure_storage: ^3.3.1+1
  #跳转应用设置界面
  app_settings: 4.0.4

  rect_getter: 0.0.1

  image_pickers: ^1.1.0  #1.0.7+6

  flutter_webview_plugin: ^0.3.11
  webview_flutter: ^0.3.22+1

  #进度弹窗
  percent_indicator: ^2.1.9
  # 丰富的loading库 see more=> https://pub.flutter-io.cn/packages/flutter_spinkit
  flutter_spinkit: ^4.1.1+1

  flare_flutter: ^2.0.1

  pull_to_refresh: 1.6.3
  # sentry: ^3.0.0+1

  # flutter_bugly: ^0.2.8

  # video_player: 0.10.11+1

  # fijkplayer: ^0.8.7

  web_socket_channel: ^1.1.0
  r_scan: 0.1.4+1
  #sha1
  crypto: ^2.1.3

  #通知
  flutter_local_notifications: ^1.1.6

  cool_ui: ^0.6.1
  #流光
  shimmer: ^1.1.1

  #多媒体选择
  # multi_media_picker: ^0.2.3
  #图片选择
  image_picker: ^0.6.7+12

  extended_tabs: ^0.2.3
  # date_format: "1.0.8" # 日期格式化
  # logger: "0.7.0+2" # log
  retrofit: any
  open_file: ^3.0.1
  # mmkv_flutter: ^1.0.10
  masked_text_input_formatter: ^0.0.1 #文本输入框 输入格式化
  #tf依赖库
  # build_runner: ^1.4.0
  # intl: ^0.15.8
  # flutter_refresh: ^0.0.2
  # gbk2utf8: ^0.0.1
  # fluwx: ^2.0.8
  # share: ^0.6.2+1
#  flutter_html: ^0.7.0
  html: ^0.13.3
  # convert: ^2.1.1
  provider: ^4.0.5 #provider 状态

  #alipay sdk
  flutter_alipay: ^1.0.0
  audioplayers: 0.17.0
  rive: ^0.6.4

  #基本flutter框架
  flutter_base:
    path: ./flutter_base
  chat_online_customers:
    path: ./zaixiankefu
    # git:
    #   url: http://8.210.39.196/pub/zaixiankefu.git
    #   ref: develop
  flutter_native_timezone: ^1.0.4
  phone_number: ^0.6.0+2

  flutter_inappwebview: ^4.0.0+4
  auto_orientation: ^1.0.6
  flustars: ^0.3.2
  getwidget: ^1.2.4

  r_logger: ^0.2.0

  cached_network_image: ^2.5.0

  like_button: ^1.0.4

  flutter_facilityinfo: ^0.1.3
  imei_plugin: ^1.2.0

  chips_choice: ^2.0.1

  carousel_slider: ^3.0.0

  easy_rich_text: ^0.5.3

  #keframe: ^1.0.3

  flutter_keyboard_visibility: ^4.0.6

  #vertical_tabs: ^0.2.0

  popup_window: ^1.1.2

  #dynamic_height_grid_view: ^0.0.3

  waterfall_flow: any

  get: ^3.26.0

  device_preview: ^0.5.5

  lottie: ^0.7.0+1

  flutter_screenutil: ^4.0.4+1

  expandable_text: ^1.3.2

  expandable: 4.1.0

#  wechat_assets_picker: 4.2.2

  visibility_detector: ^0.1.5

  kumi_popup_window: ^1.0.12

  flutter_sticky_header: ^0.5.0
  firebase_analytics: 5.0.1
  firebase_core: 0.5.1
  #power_image:
    #path: ./power_image

  infinite_listview: ^1.0.1+1

  marquee: ^1.7.0


  #flutter_swipe_action_cell: ^1.3.4


  fbroadcast: ^1.1.1



  flutter_displaymode: ^0.1.0

#  flutter_sound: ^7.8.4
  flutter_image_compress: ^0.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  retrofit_generator: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/font/DIN_Condensed_Bold.ttf

  #图片资源配置
  assets:
    - assets/
    - assets/weibo/images/
    - assets/weibo/svg/
    - assets/images/
    - assets/flare/
    - assets/cities/china_cities_v2.db
    - assets/svg/
    - assets/svg/setting/
    - assets/svg/message/
    - assets/svg/community/
    - assets/svg/user/
    - assets/svg/search_page/
    - assets/svg/vip_member/
    - assets/weibo/
    - assets/json/country_code.json
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
