///模块类型
enum ModuleType {
  //我的收藏
  LONG_VIDEO_MY_FAVORITE,
  SHORT_VIDEO_MY_FAVORITE,
  PICTRUE_WORD_MY_FAVORITE,
  TOPIC_MY_FAVORITE,

  //我的购买
  LONG_VIDEO_MY_PURCHASES,
  SHORT_VIDEO_MY_PURCHASES,
  PICTRUE_WORD_MY_PURCHASES,

  //历史记录
  LONG_VIDEO_HISTORY_RECORDS,
  SHORT_VIDEO_HISTORY_RECORDS,

  //离线缓存
  LONG_VIDEO_OFFLINE_CACHE,
  SHORT_VIDEO_OFFLINE_CACHE,
}
