name: flutter_base
description: A new Flutter package project.
version: 0.0.1
author:
homepage: www.baidu.com

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.5.1
  date_format: ^1.0.8 # 日期格式化
  logger: ^0.9.4 # log
  mmkv_flutter: ^1.0.10
  #http dns 解析
  dns_client: ^0.1.0+2
  #弹出提示
  fluttertoast: ^3.1.3
  #权限管理
  permission_handler: ^5.0.1
  # pull_to_refresh: ^1.5.8 # 下拉刷新，上拉加载
  #ijk player 播放器
  fijkplayer: ^0.8.7

  #集成有盟统计
  #umeng_analytics_plugin: ^1.0.3
  #对话框
  # progress_dialog: ^1.2.2
  #闲鱼-应用框架
  fish_redux: ^0.3.3
  # 网络图片
  # cached_network_image: ^2.2.0+1
  #svg加载
  # flutter_svg: ^0.19.0
  #flutter 缓存框架
  my_flutter_cache_manager:
    path: ./flutter_cache_manager-1.4.1
  # network framework
  dio: ^3.0.10
  #dio 适配http2
  dio_http2_adapter: ^1.0.1
  # rxdart: ^0.24.1
  http: ^0.12.1
  # 工作线程池
  # worker_manager: ^3.0.5
  rxdart: ^0.23.1
  flare_flutter: "2.0.6" # flr动画库
  my_worker_manager:
    path: ./worker_manager

  # 打开浏览器
  url_launcher: ^5.4.2
  flutter_svg: ^0.19.0
  flutter_sequence_animation: ^3.0.1
  flutter_animation_set: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  assets:
    - assets/svg/h_player/
    - assets/svg/v_player/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
